###
# Simple calculator
# Asks the user to enter a symbol of mathematical operation (+, -, *, /)
# and two numbers. The program should perform the appropriate
# mathematical operation on the given numbers and return the result.   
# 
number1 = input ...
number2 = input ...
operator = input ...

if operator == ...:
    result = ...
elif ...
...
...

# print result
print(f'{number1} {operator} {number2} = {result}')